{{- if .Values.backend.enabled }}

apiVersion: v1
kind: ServiceAccount

metadata:

  name: {{ .Values.backend.serviceAccount.name }}

  annotations:

    azure.workload.identity/client-id: "{{ .Values.global.workloadIdentity.clientId }}"

    azure.workload.identity/tenant-id: "{{ .Values.global.workloadIdentity.tenantId }}"

  labels:

    azure.workload.identity/use: "true"

{{- end }}