apiVersion: v2

name: three-tier-app
description: Secure 3-tier application for AKS
type: application

version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: frontend
    version: 1.0.0
    repository: "file://charts/frontend"
    condition: frontend.enabled

  - name: backend
    version: 1.0.0
    repository: "file://charts/backend"
    condition: backend.enabled

  - name: postgresql
    version: 1.0.0
    repository: "file://charts/posgresql"
    condition: postgresql.enabled