{{- if .Values.workloadIdentity.enabled }}

apiVersion: secrets-store.csi.x-k8s.io/v1

kind: SecretProviderClass

metadata:

  name: {{ include "backend.fullname" . }}-kv

spec:

  provider: azure

  parameters:

    clientID: "{{ .Values.workloadIdentity.clientId }}"

    tenantId: "{{ .Values.workloadIdentity.tenantId }}"

    keyvaultName: "{{ .Values.workloadIdentity.keyVaultName }}"

    usePodIdentity: "false"

    useVMManagedIdentity: "false"

    cloudName: ""

    objects: |
      array:
        - |
          objectName: database-url
          objectType: secret

  secretObjects:

    - secretName: {{ include "backend.fullname" . }}-secrets

      type: Opaque

      data:

        - objectName: database-url
          key: database-url

{{- end }}