{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  annotations:
    azure.workload.identity/client-id: "{{ .Values.global.workloadIdentity.clientId }}"
    azure.workload.identity/tenant-id: "{{ .Values.global.workloadIdentity.tenantId }}"
  labels:
    azure.workload.identity/use: "true"
{{- end }}